name=Containment Chaos
desc=Based off of a mod from GTA V
author=walter and Aaron - A
# Set this to True only if your mod customizes anything that is loaded before starting a game, like the main menu or loading screens.
requires reload=True
tags = Textures, Items, Loading Screens, Custom Maps
