name=Containment Chaos
desc=Based off of a mod from GTA V
author=walter, Aaron - A, mashelux, Brine, and Apyr
# Set this to True only if your mod customizes anything that is loaded before starting a game, like the main menu or loading screens.
requires reload=True
tags = Textures, Sounds, Models, Items
